import "./src/css/industries.css"
import "./src/css/services.css"
import "./src/css/contact.css"
import "./src/css/homePage.css"
import "./src/css/main-pages.css"
import "./src/css/servies-landing.css"
import "aos/dist/aos.css"

import "./src/css/responsive.css"
import "./src/css/styles.css"
