import "./src/css/industries.css"
import "./src/css/services.css"
import "./src/css/contact.css"
import "./src/css/homePage.css"
import "./src/css/main-pages.css"
import "./src/css/servies-landing.css"
import "aos/dist/aos.css"
import "react-modal-video/scss/modal-video.scss"

// import "./src/css/3a13f.css"
// import "./src/css/21c97.css"
// import "./src/css/82aae.css"
// import "./src/css/624fb.css"
// import "./src/css/c138f.css"
// import "./src/css/rbt-modules.css"
// import "./src/css/v1.css"

import "./src/css/responsive.css"
import "./src/css/styles.css"
